/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Comp3111.Lab1;

public class Library {
	
	public static void main(String arg[]){
		System.out.println("Hello,World");
	}
	
    public boolean someLibraryMethod() {
        return true;
    }
}
